apiVersion: ENC[AES256_GCM,data:bno=,iv:BbDdMK3ECES5ksH2cRDNnUiZYKso3SLWHNeT4GS33kM=,tag:w//+cJcvsULKb/w/N7yyjg==,type:str]
kind: ENC[AES256_GCM,data:UYt+Tuf4,iv:hRkQJCt73FKTVbI3IXUsChYD2yMRokYZ+Up/ks3JPxw=,tag:0frJSq2LBxrl2kF5qo3LcQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:B7nGDsEchryr5AI=,iv:h7dDceZCMQyea9OxtwjS1mWiwfKicD+odLtujBNu1pw=,tag:tkLndvL5Ksns/RUjvSNwQg==,type:str]
    namespace: ENC[AES256_GCM,data:moGgebz06A==,iv:672DbdIYrOShXEd/j/UJi4+NrWcA849S3r0gvYg2NTU=,tag:0NMZNpoPVr6c6SzcCfnw9Q==,type:str]
type: ENC[AES256_GCM,data:J3HKECkD,iv:jESmz73VQYkwYY30NxhJQ3CdqGeJCOQsZC4AxX0SEm4=,tag:KxVWLDkz5a0XitbHEr5JqA==,type:str]
stringData:
    username: ENC[AES256_GCM,data:CTu4ZiPdObY/gwd+ws4=,iv:nqP36h96yFV/7ZJq19dqOqBlDZaYGmUIHUVAqQx1rM0=,tag:ztJPN8kJfx9CzQjtmDFGMg==,type:str]
    password: ENC[AES256_GCM,data:llzYoiPDNAPaa9Xj30fYNuk5vTUzww==,iv:/vJ/CCsfUXqWzA50SDOgJx4QPqr0uTQBn0afNrYUiAA=,tag:R34SnFQooLwrK/YwZHC/pw==,type:str]
sops:
    age:
        - recipient: age1kutgmk5ml0lwf4u53h9um8nfdtjdzgftalpxwlwt2zt63h5l450qeyp7zm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3dkpud2thTEZLUGVLeDF0
            a2ZJa2psWG41NEcvU3BFN1Z5M2dCMGNTdWgwCnNpeXZiVjM4RHo5VVVVWUZZdE5Q
            VTdNVjNwVytOcjZQMWFxdmZjZDMwcDAKLS0tIDlJZFZ0RnN6ZVlhY1MycXY1MzdO
            dmpPRDViNzdhOFo1RDVoWVlIK1NFNFEK++IW15iLVrduVEiFKN3HVWpREid/4LNi
            6wPeddgxZ8nQwYuExLoh2QbHlvPEYqH75vUjI8nARBxBluYNAKF2Fw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-16T11:23:03Z"
    mac: ENC[AES256_GCM,data:73eN7p2rS6QlVRXwWJ6gcYeeO5dSm5Exmn5Mg/qSDAR3jYYzqpmNlIptRydM74wH2tPgbxXSDMR/PB7d8kZ/hfXqZn1Dx3NBfZmOvvVReeCTkd1ukrzE+v0j8ffvGAUNI9kVYvN9i3X/Ol5Svhs30m4mgIuoLzk1tcgo5T0NaNQ=,iv:J6YuAb7evTzhtqgNZb0C5BMqvqHfj23C75KTArdnqf0=,tag:AJjHUhUdZUnf1tp9zr+3rw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
