apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-credentials
    namespace: pgadmin
type: Opaque
stringData:
    email: ENC[AES256_GCM,data:MWmw1HS95Dx4vhcLQFTLUHvRvLLz,iv:a7ypypapFSS6r2X2al0hJuWGD6BgeUGZM2yioRjHx6U=,tag:jg+cVIVyEOecSkpHOfUYJA==,type:str]
    password: ENC[AES256_GCM,data:nO4q6XbE2wMe23rEtTbRY4CnPrDARuPm,iv:uvdkTwvpEQAVF5Hpsedbkb1YNcX3KenKqboKPVvvaCE=,tag:w9/8a3Zk29hjuI6Ntx851Q==,type:str]
sops:
    age:
        - recipient: age1kutgmk5ml0lwf4u53h9um8nfdtjdzgftalpxwlwt2zt63h5l450qeyp7zm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpc2xVc2swWEVyNnlaYk5K
            L3lEU0o3Y1ovUFo1djZGbnZSdUR4SVo2WXhZCmlBVU9GL3lGMnMxMFpCUS9oemZh
            emJLc1llaFJvTFdobi93NWgrRlIwcFUKLS0tIG5ub3ZTajJpanZTby82VHVIUU5k
            MkxoTlkya1VzZlNQcVhydTV6czkzSEkKjtW50LEhzWmuD5yudA55+0Ey3kjk/tm0
            gbbMtVlx0EXfQHEOurV03MhMhnZlBfdrfIlwh9q9GTZ9sre4OcfjHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T14:53:32Z"
    mac: ENC[AES256_GCM,data:dONCetzgphcLlwlBOKQq4KS0ElVhwORD9GWYvGShXQ2AWO1i/zUwL6fT/Go844uSPVj551WAjJia/00HvY74Tvya+dI4h1USOjLOS7VlCzlVFXCdrDdc5q3HHYj9NuESMgU5VQfg6n6yKc638V0wZhkp47c/XPySgYMVAyl0ogs=,iv:AQ2jlexqOFb9U3lLUkVl2xcUJa+mjrFdflmcv0Vl6eg=,tag:pHxFumo1x2R+CenCkyT4bQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
