apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: cloudflared
type: Opaque
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:UDEXn/0NhtAem090vbqI3xCZeexdk2Uc/8p5ePehZv0Q/9sDKPRuIf172Sc6jgXxLl4MUlCgfDQIeIaEILwa/IbedFCz3/VSID/XlKSR38i36iW+qzbNnrp701dXM7RRb1UPhiQ6FXWeXIenKSUKDzCjK+6gVh8wk3YsL95Df06kgyWoq0pio9e+XNCa3Kzt04cq234YMhT9zbcWPQh9cYBlwJRnmatFTvAVW7ry1PysEBHkak0IFw==,iv:HQ0JR2F9ue5LqGCDMXOeF/OfiwuJlHV/+gfvM2Ep9Ys=,tag:ctucAXLLXWfwTvItho1Quw==,type:str]
sops:
    age:
        - recipient: age1kutgmk5ml0lwf4u53h9um8nfdtjdzgftalpxwlwt2zt63h5l450qeyp7zm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDUVk2dlRDSnpCaEFpOFA1
            dkEzR0ttRXpBaXY0NnZ5L2pBWjRzSERpN0JNCnIzU01qbkNnM1FjR0d0VTVlWWlw
            aWx3VmdtQjRrMURVdm9lbm1vNEFXY0EKLS0tICtTb3N6MzJOUy9jVHYzMDlKbTZM
            b3I3V3hPYW1taU5URUJqNnc2NEhEdUUKHRrY/pba0P7msEH83OQFdvNAXd88atsL
            AwUH65lT7PVOsarER/cm4LNAGGlA7De5/+Z9dyIQjSonQb0HL50EDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T07:15:14Z"
    mac: ENC[AES256_GCM,data:bPUs5/+Bk+8NXjaYgVgBfKZD6ZFlehSrhS3Pj4OoIFITvftwGTyO/jWrSyhxOwboB/UH5gvhcYBftfbUcZEi/FGAfIr9T4mni1hS4TQl+MJN9IlFkJZiAh4lcrESuZtcZLp3oKQVNZUuBanVoXrWpAUqh5z/TsZw+obBomiei0I=,iv:CwLMBqHjtJ7UoMm8RtwYYqfJjycpdlYvuNcGFRn9L8A=,tag:zG7+M61tKw1kf/OReFXVHg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
