apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-nfs-pv
spec:
  capacity:
    storage: 50Ti
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4
    - hard
  nfs:
    server: 10.77.20.20
    path: /volume1/Media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-nfs
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: media-nfs-pv
  resources:
    requests:
      storage: 50Ti
