apiVersion: v1
kind: Secret
metadata:
    name: cnpg-backups-minio-config
    namespace: cnpg-backups
type: Opaque
stringData:
    config.env: ENC[AES256_GCM,data:iwTHNSZREuy9Gkt5vUSEHfoNaGVdb+NlDMa78g9NGJZT3Lp9JS9cVI/jz2sbBMt3BS4DN2vI9KpY/gDm2726sNJq3JimgOOym0LNimAS4wdiAzYiZmz0bifGnbzqq2YjK66lbjeRrsb/JizGAOf57iDEMxY=,iv:cyNy0ymGGv7k3W2+MpG9XSJfeUyA0NPfwRrD4ViKbjk=,tag:LAk/J18c6JIPBYo/4CEAew==,type:str]
sops:
    age:
        - recipient: age1kutgmk5ml0lwf4u53h9um8nfdtjdzgftalpxwlwt2zt63h5l450qeyp7zm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBidXNnR0tDTnFRZUo0dEtv
            cExOMHh3NXRlN0YwNzBSVWZIK1JmSUJLbFdJCnBFSXVIZGgra3R1bVE2V3ZMblpN
            ckw5OXJtUVgrVU5oMkFrWjZFNE9xMFUKLS0tIFNnellNd3ZPNkR6NDhBVmtOWTNU
            TWNNUVJqSjVhTTMrRW9ZSDhneGFEdUUKYA7iJET3cBJXC1HlHus/ZbYSqpn+oME0
            xr+qgkGUu0h3v/mcXvfHOrKy57IIch3AlFeh3Upp0ERciKYUNxaEWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-05T01:25:17Z"
    mac: ENC[AES256_GCM,data:sIvd1dNLJq1vNRLdnqwqG0D90E9Hfd8JTE/rnJrT47fnWxx1Riypwi7KRmWkaZGpH2qd6C3xNYHVfBxorsQ88kmaeMERIpbpV6uKXnuWIBPK3xdlPxaydZrAED346GZG7zrivyuliFhxehZauH6L4dvilvM6lo+PGO9D3CcqsNA=,iv:UHT+c2RXI7os2DAn1H0XFJAzK/AqlMqI5XvjEve/Vm0=,tag:I88TrUn0RmFWegEj0t1u6Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
