apiVersion: v1
kind: Secret
metadata:
    name: redis-credentials
    namespace: redis
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:o7GoyR9Cse1sSCAIOONDa1/KltjnhrgSZPIfICMszqs=,iv:3SMkmJri8+22ISDXbvP3Jl3VTaRERxAhFvjh1VBvHH0=,tag:3luGbSSDRRhzG/7wbkS1xw==,type:str]
sops:
    age:
        - recipient: age1kutgmk5ml0lwf4u53h9um8nfdtjdzgftalpxwlwt2zt63h5l450qeyp7zm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrZE5WVGQveWYxaExXc01I
            UDJkc3hWNXNUT0ZoTFhHSkJlLzJzNm52dVJrCncwM01jM1l5bHJRSHozN0c4RVh1
            SW83UnpBZXNjUWFibGtVL0l0MDk1cGsKLS0tIFJRVGxFZnJyaEcrMnZmc2s4NDdp
            MmhOeU5PRHQ5NUpHNE9kOWNGOUZacjQKRmnqSos1rxfCrAqXOLD6pVqdDu1xE7KA
            h3yDm73eQMT54K3etA7y+iHisQpQ5t5KtLBaRhhic01vtOfVWObUGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-02T10:06:09Z"
    mac: ENC[AES256_GCM,data:mI7zLVOYvEF877p4u0NK+wjm3DASzs4pPib1ZMZxKv4Dq2auTNeQ4lmlWQMwKIPQVb+2oWHy4PmvVumaAUihrX9EhyH4rXIhVwqVU4IMX0EGBwIQlexgwCuQNfANJ6rzOrgmgLlbQ3eC3gcg/ZK+QPoB12J8yZegkJBSKp/kjIQ=,iv:jKqTUwYMkjcedB/+FbGWU3YhQYoRaeQaJ5NgHGSPIZ0=,tag:tgFMarTSOLzFd9I4oHqApA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
