apiVersion: v1
kind: Secret
metadata:
    name: cognee-db-backup-s3-credentials
    namespace: cognee
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:CCWdgupM83by8eCD0Cbkx/7TabY=,iv:0HH61sBbKEFpSqDBKXzMBf5cA9ooI+oZyCuon+/NTqU=,tag:gwXeENmENQwq2T57ZVrUZA==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:FSh7crmjShBFZVaEyPyHq5b8UY/ZtZqws0cIjqVBw7jig75Z2eVQ,iv:StYe5J9EIaN3W4tvpCLzVh6X7pArXRwjbbZnhbCmc9o=,tag:ZzKSuDqqdmHviG+v67Qb9Q==,type:str]
sops:
    age:
        - recipient: age1kutgmk5ml0lwf4u53h9um8nfdtjdzgftalpxwlwt2zt63h5l450qeyp7zm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCVmVmK1FOY0hjeS9qSWtF
            TisrWGMvK2UxWGQxQTNoVVozZ0lSY2Y1V3pvCjlLUmNHSWdYQmtrMlkvVHF4OWJy
            TWtuZEFyL3pFbnBOT3ZqQ2l6QXNOdnMKLS0tIGpYbzJONFBZU2hUaUt1RW9jK0dL
            bExDMVBwazQzZkF0NW10cGNsQnEvUlUK8qey73sr9Wuv8boCMfiSyBO3TgSPBi8I
            TFRIDmhoK7UwH26GNZyPIwtGsIPlbSIHSPm2DWVpO06BUSAL4PjJvQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-05T01:05:48Z"
    mac: ENC[AES256_GCM,data:pZsrZxpuxb2NUbQWC/tzE87qhlO2E9ozkTNvBSXBL88tdw035Dgj381OiRl9xK0aHGl0MDEABNcMHYlGjveborQcsSuOKPRmCCvoBior6YY4Ziqyg+nvIKcFmeC0ZC74K7YGCA9GrsiCyNbcHi8FGA27sp3+ge9fZ6joJ9mXgC0=,iv:FwiryCp9I/HEPQMZBQSNc1m6fRDY4qBaKMm3Jw+74M0=,tag://o9eL6w6Fkl7/xzaeryTA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
