apiVersion: v1
kind: Secret
metadata:
    name: buzz-db-backup-s3-credentials
    namespace: buzz
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:qIRj5IANwZxl0cjNNFotlqSUR18=,iv:f1iRWUIweUHtVcdNTUtAgjZCG1pPeLRovFMC/2+Qt0o=,tag:Pugv/faH122MOqsyXcsS7g==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:QK09bV0oyvdm7t/CCg3Ql+YqHc9w+yFeSXDukQnKAhzgH26K2Pv2iw==,iv:G6LIx55IU+J7vo0ftXcUB0aj1oV0WjxqPLLoIwL5vdo=,tag:je/4QTs8Lb9dgepXOR/8uQ==,type:str]
sops:
    age:
        - recipient: age1kutgmk5ml0lwf4u53h9um8nfdtjdzgftalpxwlwt2zt63h5l450qeyp7zm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRa283RVUxMFd4eXM1WVdV
            d0ZKbldZLzZrcDdlZTlGU0dVQ0d4cFJHN3hJCmZTNHF2cmFHeGJVWDVmWVVOT2NC
            ZnI3dFN1TnFGTndRWmxiZ1A5eGNoWU0KLS0tIHFMRFNPNmkxZG1NWjNSckh2RVUv
            bXQ0QVNRR3hNS3czQVBXdTh4K1F1MGsK1dI4YDek8w/PiRWkryrFd0MAj67MUr36
            c69AX29R1hFyTXA2dYTyBC2QQU/tgX3oepId6TghOwK6i16feh72rA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-05T01:05:48Z"
    mac: ENC[AES256_GCM,data:QGbs36ANfXz8lMJrG3P1J/MIbXj4K6U+rtv8O8dXxo3ladT9JT+qpaWaCzeL3gtD/Bj2i+6wG0Nki5fvhs7JM//SgMZEoe5BcuUXVY4QEu3GmrupAKc/q8R2tYj52m37NLJbVijst9Vm5XJgwRLXQCvbHEL+OGnv/7qpIFYYUqI=,iv:qEFV3JIU+uvEZ63mxux6JLgyLGPl7ImJyNaIjuZVuUk=,tag:kXxxzHDcfN2YdxkWfZ4rPQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
