apiVersion: v1
kind: Secret
metadata:
    name: buzz-db-credentials
    namespace: buzz
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:AOdJKg==,iv:tpS3RLztk32C7Y20Q1mO52cjdHYBYQK7Mjt5or9D84Y=,tag:AqXwAM8dt3i0nkRLPFLqTQ==,type:str]
    password: ENC[AES256_GCM,data:ArrZLACMxywZCwmvVhc7N7KfJ83xJPm+3lVhfkDJ8Js=,iv:6id7Sh4E0rbCy+0KKGdBFsAUsT3yt6PpeuMdYS8WLn4=,tag:V1XYzW3kZZkjxe+qlfJEKQ==,type:str]
sops:
    age:
        - recipient: age1kutgmk5ml0lwf4u53h9um8nfdtjdzgftalpxwlwt2zt63h5l450qeyp7zm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJcXBQTXZUSjhsTk9lTVFh
            YVVZbjFCV25qZUhwWGNHakZHd0FJSndJSGo4CldIVGNjNkJUZld5VDU2VENybkt6
            SGFBK1VvSXVXaXlObkV2ZzU4SnVpWmsKLS0tIHdCaGticnN4NzJkUklqaVNNSE5H
            bEpyZlR0U1pNMXJlbHZneS9MWTFCVkkKF+hwgl44X0QI77aoyndCl2Kv8iZ8EPEb
            qXjKkvvOy9LCsy3mXA0BhYEGCUTLa69hR8HOoyqJmHzhMmWsyDlEwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-02T10:07:05Z"
    mac: ENC[AES256_GCM,data:H4oZFqj7HIUyGe8r/8pLVhcAaFdOi3L9RchPn4Eo+ZRjHqfbQwTaV67+ptydZbANN3YPHnGqwWyFvcQg/5oyObWLRhaKAyZSO2murYkVkdrCarAOt9IxOG80XJqA6w+GYN7TpBpXbG1pFDH1ZWYknccpknQS2LwFwdLWiANSvWc=,iv:xOnXrpn8Xayvq1wHjlkt1yKr/uUFSk1IwIjIXpRYqew=,tag:R5AKE9IFf9v5PEAioC+AIg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
