apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hermes-role
  namespace: hermes
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hermes-rolebinding
  namespace: hermes
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hermes-role
subjects:
  - kind: ServiceAccount
    name: hermes-sa
    namespace: hermes
