apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pgadmin-config
  namespace: argocd
spec:
  project: homelab
  source:
    repoURL: https://github.com/IonBlaster77/homelab.git
    targetRevision: HEAD
    path: clusters/homelab/pgadmin
  destination:
    server: https://kubernetes.default.svc
    namespace: pgadmin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
