apiVersion: v1
kind: Service
metadata:
  name: adguard-replica
  namespace: adguard
spec:
  type: ClusterIP
  selector:
    app: adguard-replica
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
