apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguard-sync
  namespace: adguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adguard-sync
  template:
    metadata:
      labels:
        app: adguard-sync
    spec:
      containers:
        - name: sync
          image: ghcr.io/bakito/adguard-home-sync:latest
          args:
            - run
            - --config
            - /config/config.yaml
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
      volumes:
        - name: config
          secret:
            secretName: adguard-sync-credentials
            items:
              - key: config.yaml
                path: config.yaml
