apiVersion: v1
kind: Secret
metadata:
    name: adguard-sync-credentials
    namespace: adguard
type: Opaque
stringData:
    config.yaml: ENC[AES256_GCM,data:MSJ6pRGgLzYnWTJBjJoeTPLRPMT9FkvpbjQdWf0fCC+X5eY1Sd4pJydQlXrixvCi9LfBvsULjytsPdBTnL20cdWHlodJeT6qAIkZ9pBVbg1OmGjGKUNdAN2nX1J2+u48dLlcA9LUjMIrUjy+88Hz2rfoCk+EgtPPPeffJBt6Ubp67PseU7BdYCMRwhOpaeYUOGPqdnT+wtQEiuv5RjM5Xx6MNPSxV9snw4rNwJ+PB0OXJqNIUFN2dmfZNSz62WkpOpTNAB/O6hvqkcVNvRG/LGPAA/bNdnuKBlLqEPI=,iv:3/WPzd4ziGrGp+tWrm3n0X12MdMDJZ3nDGvunadSY1I=,tag:COPkdN9C7hqMsZDFt1lMoA==,type:str]
sops:
    age:
        - recipient: age1kutgmk5ml0lwf4u53h9um8nfdtjdzgftalpxwlwt2zt63h5l450qeyp7zm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsdWhWMkRQdmxBZUJWaTFC
            cGQxa0c0ejUvT0RQWWczYjlKOHVHckhHUzJJCkNkd2ZqdzRTMnJmK0dvVXlWUFlQ
            VDdKV3VUVGh4Z3JnUEVvbHBqZVNuTGcKLS0tIDc3S1ArY3laRWY1S2djWjR2b0xH
            S0F6YktEalFZWnZxVm0rUDRzWjY0ZVUKemXJxjteDrsjKuk2rHNNgzAOX74w3MDt
            OFU9hAtADnTkocbskh2JXh28MdnlKl3wJ/CQF/zwUGTIcl3F6pYqKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T03:37:20Z"
    mac: ENC[AES256_GCM,data:U9ulBx2ob/4Hip7xDPPlJVf9M+J8BoHWO1Jq44zL9hv3OAfY1lf8sgW+jDjr1zlxo2pS+9QShRroaKur53IyP8n7PEiSrQRWHzPZDYgfNq/VpW6VU2BXgz17oi+aXWRYCiqCpRDsbmoFZbAl7yu/8/X828Z3tUNamJ8CR1+pfio=,iv:Uc5uj5CQnHQpRsGoTgODF2buqcKwmR6dQhRsF+Sl6nk=,tag:0T/VPnt0LRf7MHboFa8eVw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
