apiVersion: v1
kind: Secret
metadata:
    name: homepage-arr-keys
    namespace: homepage
stringData:
    HOMEPAGE_VAR_RADARR_KEY: ENC[AES256_GCM,data:TlQgKIq1dUfJwZhGNPKPkif9t6FYMcUJWuoMnz6SA0o=,iv:RY17odMCWS0SjW43uNdaT9EHc10zYVpXaCALGyto/30=,tag:2FR1sy8HDT1JZYQYLuXzBA==,type:str]
    HOMEPAGE_VAR_SONARR_KEY: ENC[AES256_GCM,data:jxqEyg0chASOCfJB1C2MYv0/MLN30oKw8XRIeet4li8=,iv:nlm6BlscDX1xVBJUN7u40a4Xrn0icGtidt8pd/usHmI=,tag:Qr7TLfhyFgYRTjO5st2wXQ==,type:str]
    HOMEPAGE_VAR_PROWLARR_KEY: ENC[AES256_GCM,data:QpHkMsRsG+lrkCItJrm3DwsLJzZLz1p/GsOu06Z8dbg=,iv:0k7ATfod9cGNavsVcKHBCSyDdmPxG8b0yHikv9P7JYw=,tag:hkLaoOix3zGBqiWReLuyJg==,type:str]
    HOMEPAGE_VAR_BAZARR_KEY: ENC[AES256_GCM,data:UhyHD0nw8clt6Xk7W5qHovaJKagGofaQ1tbdgICl2M0=,iv:8HoUugSy3oOlnd/A+u4z4ABzyAC1b5hVwYBg6Ih1xhg=,tag:0C5fOhatUOeLLxqmxQr88A==,type:str]
    HOMEPAGE_VAR_QBIT_USER: ENC[AES256_GCM,data:RhWg2b0=,iv:9unycR6dylMjHA09a304Jz9wAg4lFTl05xRe8zaXN98=,tag:HAmOKRWipxNmCDZr4QiLog==,type:str]
    HOMEPAGE_VAR_QBIT_PASSWORD: ENC[AES256_GCM,data:8mbmFwFtM0pAtrXUGlxhDCmOAWDRfIl2,iv:7PcSlM6FsX0DWg8jHztX8f5tXQ6wM2lNfJ/H6j2+Vuw=,tag:WVRHpFb8TcpvIqgVsjHdRA==,type:str]
    HOMEPAGE_VAR_NZBGET_USER: ENC[AES256_GCM,data:7FbcRh4x,iv:x/ed7L+c2p39qYwWVf+wUdWCZjVHJO63viSTLjZDQ+4=,tag:/fxK8PtRcRWc3/wzGNgxDA==,type:str]
    HOMEPAGE_VAR_NZBGET_PASSWORD: ENC[AES256_GCM,data:n/cmrro3PeOTuw==,iv:bKRp84vs4fpNXAX//Ii17bQdfytOfGTQNTkZluEXoFk=,tag:iyT1khqRZInrveryE9mNwQ==,type:str]
sops:
    age:
        - recipient: age1kutgmk5ml0lwf4u53h9um8nfdtjdzgftalpxwlwt2zt63h5l450qeyp7zm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYbC92czZBNjBCZU04YUwz
            OUx5cE9Ta1ZzNklyODF6UnJmOU5TVkErTHhjCi83VHlnNmYyai84di9kRnNJbnRP
            V1ZBaWJjK1ZRMXAvUW45M1NGUG5HSlEKLS0tIE9zTm56dXd5VkJQSStXTTRRZ2Mv
            akdDdXVmOUZ1VUdZWkI1aHJKZjZRLzQKUpHhHxdwTeCwdLBPC4g0/udnGUnEisF+
            mH4si89gcraVTlcLMm6XZmCaTW/TOdLhvooyH1Z/bvCXOpTUi8vxWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-05T09:11:22Z"
    mac: ENC[AES256_GCM,data:T0q/ByPcE8eO4FdmmV61/uCNlCNGwPv1PQ/Y0ZuAEGSB+KdYuD9YR/Ev9Uayn2O9x2K6MYRlQC3t7iKCj+3RXg4W+B8u9ox7ZQx/240gBYlbnEmka02/8oO7E5BUrP6mlll4miPe6qd6/PbkuOBjK0fPBtgWekPXJAQzKGpokcI=,iv:GALiV+fElvu0oZf0fgOKYINwUTk+I0iwkBuVFdPkvTk=,tag:qymJvD/f5sTs3wBjpK8uOg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
