apiVersion: v1
kind: Secret
metadata:
    name: homepage-synology
    namespace: homepage
stringData:
    HOMEPAGE_VAR_SYNOLOGY_USER: ENC[AES256_GCM,data:8PWb78U=,iv:c9iIoh0/zxconSyBT39Lp7cnPKVVQcq2kbkFBT33wF4=,tag:vhrUUpbpjsRKpVR082ArhA==,type:str]
    HOMEPAGE_VAR_SYNOLOGY_PASSWORD: ENC[AES256_GCM,data:f/1TWiVRxhKcP5kP,iv:+V4YVj7EnrCp80CxVWx9mutIikDxZPq63w23gnoQjko=,tag:FQBE58ME2Agz14h/RRxMXw==,type:str]
sops:
    age:
        - recipient: age1kutgmk5ml0lwf4u53h9um8nfdtjdzgftalpxwlwt2zt63h5l450qeyp7zm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNZDNYOEoreHEzRmJMS1Iv
            djlrZUF1T2xCMUlCQk5pTXQzZGJsQ25FNFU4CkZuNHZyTncrNXVramFaNjVHS2dR
            T21KaUFBUmVVK3Y1K2hIeVZrb1RkWUkKLS0tIEdNOHlRajNtK2VTRWs3bTQveHYz
            U3JPYThCMDdlS3h3UXY4YnFPSnRCbFEKnSbCzgrxIEKxYIC6lR+eoGMgbVl5Dzq9
            EvpkHlenwLaIb2DPyCYPvw6TA7tYto5ZhkrC6kgVuXCbIkv4UqKJDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-20T07:00:29Z"
    mac: ENC[AES256_GCM,data:ZYihsGiGZ5OMPUyPkSoDGnQTD/Ilp4txPxZBb1HblCUYltYf3dZWWX0irhaa1Z9imPWI38jq9pDj5OceLobApSOl7xgKbAgcDw1bXbssSdMlXaul0UIjgoT7UD9KULWF+2THMY3vNg9H/57KttQ1MzLQzm3NJ5GMdW+HoHCH05Y=,iv:N6+79y+yVycmt9nPZPLF6lhmvurz9PAQ0VKwcoa85dg=,tag:5WafobHXzsBYcQk3PgDcZA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
