apiVersion: v1
kind: Secret
metadata:
    name: homepage-synology
    namespace: homepage
stringData:
    username: ENC[AES256_GCM,data:iquA0Kg=,iv:jtIY0a7f53nds1QGv2tOKpkbxTJHbWzntHccHPJbkvU=,tag:akeGilwLg3J5qHOr2UbLGQ==,type:str]
    password: ENC[AES256_GCM,data:kbBbvI0kyPtawxjO,iv:Z9IaJIIj7NlHpFmoPaTDWV9lWznnUJZ1Py9wvImb570=,tag:A4+wgH+OIr/+tTik2+GjGA==,type:str]
sops:
    age:
        - recipient: age1kutgmk5ml0lwf4u53h9um8nfdtjdzgftalpxwlwt2zt63h5l450qeyp7zm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqNCtLN1FMcms2STJjSGJ4
            c3dYVjdJNURyWXEzOXJ4R1lLdkhQL2xNZENvCmVlMkoxZjEvTHJZNnVTa2NyMWdV
            bTU2MjhuMy9lWmFNR1J3UlVuYjhjRFkKLS0tIDkrYlZRUE9DOTRUTm5SMHZUNW9t
            b0p3RXJZZ01vTTZKaFQyejJ2RlpJNmsKB2OBkfc1dU3QgHEr7kYEDmHhI7ItisYh
            1h2n5p65SPJNN+79+fUTrl9gg+y1ppZ1a/TyT9YYQ3kc4OrMazMzuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-20T06:45:32Z"
    mac: ENC[AES256_GCM,data:Q/9fv8Jpq/3s9kXEDzNk2UNpZtH0C8CLIbTF8TlgMmjrvuxUR42Y/OPNKEfLDFzfS5sPLbpC/tikW07yqQVOdexjFJuQ+8IkqfBmPVnCYgFCsQPj0WAUc3hYMj26TqVnaOiJGd0QmXkdR2Ek+Bx73QjQFVVi7JOfUtfxsTp7Els=,iv:GnGEp38lGrlkUwa9tRDG6XGZvi2TfgLH1byiFGu/1Xg=,tag:Efbaonf7lAdLydKopKgRAA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
