apiVersion: v1
kind: Secret
metadata:
    name: buzz-webhook-secret
    namespace: monitoring
stringData:
    critical-alerts-url: ENC[AES256_GCM,data:AHwD5CV5fO/UTs7cqboM+tvB+4uHZzA/Ev7QWohu4htnPkVAY9q3MrD+p9BCoI0+HVJSlTE8v5ARFXxS8Rhx6pm+uHvb/PwCuzRs8KlMMs7CwO6le5ydBubrsav1VTgHkQ83bAmdH4/svlakwc9FW7m5gw==,iv:g5zVhbtDqJWLVAC4rvvjWIy/8bHcI49UbkY7cKdd1UM=,tag:zHpaUNqnIWf54dWQRrQgTw==,type:str]
    warning-alerts-url: ENC[AES256_GCM,data:yts7Lt2lQX3y39gHXdH/R78JiZO/yFBcdORemMjmlX1mvafNVEgAmaADo9QOQDy9+tvUEY7NsEoUWEm5PayvlCzTrZwzFHRzsBT4CYpmVHZtsuzwaoGwwXuSRCzjER8+fTq5UAn3y74cT6IivoP8tYLrHQ==,iv:oVDLktWpavubepVo5IHHjRSezAfMA1Vf1rJDHBiNLqQ=,tag:En+flffZNMOxuZPEc6ntPw==,type:str]
sops:
    age:
        - recipient: age1kutgmk5ml0lwf4u53h9um8nfdtjdzgftalpxwlwt2zt63h5l450qeyp7zm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNa0F4MVpJb3Zkcmxzak1o
            b2pMZmJMOS9Ja1JiM3VmaGExTUVzWmVUOEhzCk5pQTFkNC9zdUFUaUFDTEZNcUs1
            T0tIdWcvbk9ROXdUNVRSeWJSVWI1U2sKLS0tIHZIUGNDUjZIakhudG9pZVlSY0Nw
            UHF4MUxLVXFXVzU2MEhIdStiUDdlaGMKtvYRPC3USwNj61oGPLUIzX7InPe6AIfe
            WEsvkanULF5KWKUbDvJUcCgkG1oUsx2S1Nqp1xg/BlxTNIXi6uVhOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-03T09:42:12Z"
    mac: ENC[AES256_GCM,data:PQHmGGDiFj7wJVLOs0F7x9S4N2WgK3C+gJZFxKTwp0csiekoB0fZC9AT1Vm6YRtJf917kwNnUMh722KumZK87y3grUk3XHxIB5PeTuI76E8oRsE7hugDNATsbe2buKV5kwjJI7k+AGS5qczYEnNaboGtliAY0Hg7KchKqF8JHhw=,iv:6n67xM42W98TNVvXdqtncl2yl7r/C7NDSTiWEJ9z0m0=,tag:KtyCUSSrgK0pwEe5TymfEg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
