apiVersion: v1
kind: Secret
metadata:
    name: buzz-webhook-secret
    namespace: monitoring
stringData:
    critical-alerts-url: ENC[AES256_GCM,data:5BV4t1UkuhWPp7jH2mHGUtXkKx7ywJTOilbwvAQ+zmC5QRik9CbbjPQ9j1vyFxOopF/UT+JAdpFtiQ8WlapMO/u16fJ1jHujcL2eorAswMP/oYW/5LREGV7VjVoRyMiz2HJ37G4LDg1lTcNsR7OOvm0OCwfItn4egtfFF403,iv:RLF0yaUIw5bUVi4ki3ibujf7ACH5FBf1BpnLHn5abJE=,tag:31JjtiPz0afwbOFawicL3g==,type:str]
    warning-alerts-url: ENC[AES256_GCM,data:bOId0ghdipQmR8Q8dHkJWHRd+VsWsMuKEiaEWqflFknXAIvLq7bjQ77AjaUNP2nqSwVOJoB6pfYU2LE322N8WDF8xybXDgOvygosTgTwjYJMqBWUkGixDCdqPbYYFttrD20CUyYnpX9T2kxfjh2iQFfzdWPH7iKI721wbQsP,iv:+rOGtQ1DDgZSV1My4pkbu87Zyg4s4YVw4mmMBYkdYrQ=,tag:QBcyBLh2uWXwH+6OYyZH4A==,type:str]
sops:
    age:
        - recipient: age1kutgmk5ml0lwf4u53h9um8nfdtjdzgftalpxwlwt2zt63h5l450qeyp7zm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNa0F4MVpJb3Zkcmxzak1o
            b2pMZmJMOS9Ja1JiM3VmaGExTUVzWmVUOEhzCk5pQTFkNC9zdUFUaUFDTEZNcUs1
            T0tIdWcvbk9ROXdUNVRSeWJSVWI1U2sKLS0tIHZIUGNDUjZIakhudG9pZVlSY0Nw
            UHF4MUxLVXFXVzU2MEhIdStiUDdlaGMKtvYRPC3USwNj61oGPLUIzX7InPe6AIfe
            WEsvkanULF5KWKUbDvJUcCgkG1oUsx2S1Nqp1xg/BlxTNIXi6uVhOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-29T02:05:57Z"
    mac: ENC[AES256_GCM,data:KMM5OxygbNXdKNLcJdAMd5VtC5lHumKwtHRZDQCwr4CHcjYZatzthqeCdEqhQpFxNsabrsL0QWS/TYUPUEulQVuPlVGbB73PEqgGxh8+qJBjecJhiaFLVlkL1W8t0PyV5xYHC8hGRWSek2RPcI7wvIyrMEw60bThBfwu3/ywmMk=,iv:+LYIQOCcSys5yuNw3VpV3Yay49Ab6DpWz3KjUKndFGI=,tag:6dpWIBnQWvcWH0fre6e08Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
