apiVersion: v1
kind: Secret
metadata:
    name: buzz-webhook-secret
    namespace: monitoring
stringData:
    critical-alerts-url: ENC[AES256_GCM,data:AHwD5CV5fO/UTs7cqboM+tvB+4uHZzA/Ev7QWohu4htnPkVAY9q3MrD+p9BCoI0+HVJSlTE8v5ARFXxS8Rhx6pm+uHvb/PwCuzRs8KlMMs7CwO6le5ydBubrsav1VTgHkQ83bAmdH4/svlakwc9FW7m5gw==,iv:g5zVhbtDqJWLVAC4rvvjWIy/8bHcI49UbkY7cKdd1UM=,tag:zHpaUNqnIWf54dWQRrQgTw==,type:str]
sops:
    age:
        - recipient: age1kutgmk5ml0lwf4u53h9um8nfdtjdzgftalpxwlwt2zt63h5l450qeyp7zm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNa0F4MVpJb3Zkcmxzak1o
            b2pMZmJMOS9Ja1JiM3VmaGExTUVzWmVUOEhzCk5pQTFkNC9zdUFUaUFDTEZNcUs1
            T0tIdWcvbk9ROXdUNVRSeWJSVWI1U2sKLS0tIHZIUGNDUjZIakhudG9pZVlSY0Nw
            UHF4MUxLVXFXVzU2MEhIdStiUDdlaGMKtvYRPC3USwNj61oGPLUIzX7InPe6AIfe
            WEsvkanULF5KWKUbDvJUcCgkG1oUsx2S1Nqp1xg/BlxTNIXi6uVhOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-03T09:15:18Z"
    mac: ENC[AES256_GCM,data:X0q1PNEPTtQ3Tc29VhAiD9UlP9Z5H5c2F33W4LfNJ8cL1ouXxRMR6oWHKvF4vTNdo8iqkJrAxSHcWvgCemBkjMduaepDpDrHHL5Dihwyb+RgBsVLszzoxHXVD/LOIArLI1ZBtVUeNLqzUrlZNhSO/OKFbIhPFI82cs4XO/t8sPo=,iv:xwinf4bZwuiFz4lAdTFEbZyrV6Np7O6nMpLjg28YK78=,tag:L1wp4e7veSmss4fHScKQFQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
