apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-user: ENC[AES256_GCM,data:In9oNNw=,iv:leV+ClDuPCKlT/Te8aGvygofKc+v67v7SFz52N7Zpzk=,tag:LE2G/Rn9hYMi+KVt3b+qpg==,type:str]
    admin-password: ENC[AES256_GCM,data:M4mXhv3m5aNfswFIBRsbWehG+puXWydxrzfieoTlKDM=,iv:7/Y4UnumiagEMi+5XNns+Jptt44OTwe6XGZfyRnruoQ=,tag:iLw87htw0Baq9oHXMP8e+A==,type:str]
sops:
    age:
        - recipient: age1kutgmk5ml0lwf4u53h9um8nfdtjdzgftalpxwlwt2zt63h5l450qeyp7zm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwZkxqdGNobEI4TkZqUTFN
            WCthKzlMZ1NwMElEd2xLekoxMmllSnJRNUJjClpXSHB4U1lYbWh3ZmJZNzhIMm9u
            d25IU1FqSVl1WTJ6dUVhZ3NoeWJqMDQKLS0tIFFmRC9VUFhFUlFCWW8vK1Vza3RT
            RHNkRy92OGxkaDFHUkpLV1hqbWgzTXMKET6S+JR0FgvVeov+F+E8GoK311qmegEj
            OoHimZlQmkUd6t7WWYr9O6R0PP3s4/IWBScMwY5VA+m882F4QlnILw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T04:57:56Z"
    mac: ENC[AES256_GCM,data:0dCx6rKn21AP7B8ZRFVYty6nQKpphAHi/RHZi9FR8Rq/5auOuqHvRaBFoT3oau3QnNzRvheI5IbDZX00/fr9c5kbZQ2m3JCJm5XK/a+aBVMjoVa/6oDqjyWY4HBHti179nYtYANiI81yCCNoPmzv518ghqQW378bB5idYqWmg8M=,iv:XbNmbYcE2j/wxZcrRud82KEfopFmWWN4UkLACQqkbho=,tag:aMgunQF+pNaA9tBIzhz9VA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
