apiVersion: v1
kind: Secret
metadata:
    name: grafana-db-credentials
    namespace: monitoring
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:iJ7jElKw9Q==,iv:38uX5ie1JNS2249dk4CO4gjWqLHnbmsYxxkJOgESoxQ=,tag:H16q+KK/PVSXkLOl34WXrw==,type:str]
    password: ENC[AES256_GCM,data:bDAdtA88Bnh3bNNkfg8uCACaVlAsLjr1+FytU27OgA==,iv:IigJtMMTelQ9SZ/+w+ZLI1wzQ9BeSm81X0SxjbT61IU=,tag:yCz8U7PD8qxFwGFXaXW5KQ==,type:str]
sops:
    age:
        - recipient: age1kutgmk5ml0lwf4u53h9um8nfdtjdzgftalpxwlwt2zt63h5l450qeyp7zm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYU3dFeVJzU1lVaThhNDk3
            MHB2V1ZHUmNScU5XU1d2M0VoUkRyWlkyQ2xvClpkbGJ6aE13d2hRdXo5RWdwZFY5
            TlVYL2g0Q3dPa0J6YWsvNFpiZ3h3enMKLS0tIEZOS2ZnY1YzNlFhMXZDM0Zja016
            cWZHTGtKQmhzK1RHSExwS0tOcDFINEEKip0XdGU89k9p/UFPQo6K2f/WccNI30uY
            c3ZIz7uYpJTeBqneF79bB5VdiHv/Ed3WcCDwlXuruZFEeND6qgkORg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T04:57:56Z"
    mac: ENC[AES256_GCM,data:+4NiWunOaiZpBAEB5rN/lacBokjL6auUDcztKa0AbAlvX5X4HJRGyXaN2FZYSm//MMZIPIyq+Y84T6nyzoTYVfk5BwQvf0iVHx66cxsRzyKC+WSg2+wXcDZjFlm+3vfxLbgTOr2Is/TiKy65CUkih+EXoABsMDJNUj6Z31olBjE=,iv:U25QDtsmpnFpLnZ3rHJ65bXPDMMaJN354+/eY2jCJkc=,tag:qGbJ4FIMCWfKiGageKmXZg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
