apiVersion: v1
kind: Secret
metadata:
    name: log-digest-webhook-secret
    namespace: monitoring
stringData:
    webhook-url: ENC[AES256_GCM,data:fta97rTcpsyzrgy9AawmALmwo7N7+gsFEmJC+iGLZ2OepSSgTx5O8vnl+gLEgI8kFJaDgHDYvMdUHlSjOnKK2g7TpMmFppCtiPks2Qj4nFcI82NCyDBJaYUlJ5IY14D5uYkS8ZzSLQgtum4rmYqdmMy5Mw==,iv:SxLMIFsLvZJ4wtwa9orzOAc7VeyGxj7FIcJr3ldaVig=,tag:Z/0CLsxje5IHbHCFrejx+Q==,type:str]
sops:
    age:
        - recipient: age1kutgmk5ml0lwf4u53h9um8nfdtjdzgftalpxwlwt2zt63h5l450qeyp7zm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPR3pibkcyditQRDlDNlBo
            anMrKzV0WEtMWWcrdmswMWNMaTZkWXdwcXdnCnlrQWpSR2pCL3JHR1pTN1lXNmRn
            QWtFanJRU09zMWZVQ3hvMmxVM3h1SGcKLS0tIFBiN1N4c2JnNHdqZ000SXloNWpn
            MU1wZXFmNnI2RitIbnlGa0FGNXB0R1EKifpjHCTLgvPOXohpMK5j7GU4u0sZF4n1
            3U8i4M00uUzXW/KK1Vq3ZBLmCsSSyrnN5ootI2dYU1HSMpuBOh7Sxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-03T09:22:48Z"
    mac: ENC[AES256_GCM,data:37aY7n9Yz5dkKM0BqBDulKFS8hw3YK32MhKayCmD0THWQYs36WJ6RqjKWztAYtu7rfVuOlh//Sx6gcxTqZlr1JhY6xOgfobEGApS7utUrsu79PvhVrigeGiak20MDBWEPUexH12XD4PSivpCWhg+MZ9QJexD0nVGIBxJ1aSYZdY=,iv:FEePOFEyil0tC4fHJStxLLxYlnP63eewx08n5jO+V74=,tag:JzC1f6ZpjT1DExkGBaS9nA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
