apiVersion: v1
kind: Secret
metadata:
    name: mikrotik-exporter-config
    namespace: monitoring
stringData:
    config.yaml: ENC[AES256_GCM,data:RQkMQXYxY3tBj4xbB88YqBMzfqoFSONhqFRmcNys5zpa4iAYjdnnHGdx+zAAkECHN6Vh5v8Kw7NqzWPDhgAvs0kAIH7I2DE8bukz19G/OXJ3zrFSdOzkWjQsXWy7TT/+VG6gjcpsJjms9sd2xvtUjfAZyzx8+McXWY2cUz7U5Iyj6jtdpvHEgxfc/0e92p8Si3BzXt1ZPZAD6FcOLhe0WIsrLdt2PDBhA+D6pCoZUBiBFtcRSVMEE8pcKBcb1p27zClhxw3UkT+5VTwJ8IlB7NEd1VMO7QhLJfkJLjS0cINvi9pp3foCDpbmNXCtph+rbaC9zVhEmGxXUFVd6M3bEcDvIjkziMMRLiwdPsRMyFzp2lx9pKaUtMOC1TIIbJGvbKvH4NSq/y4duua8vIXVa+ueJXhB9CPVtiGE3OGInrs9mFYJKnnSvg/N/MLYRPlNh2zong==,iv:10726ck7asRdNG9aCeXib/p/uW4Gi0WBE+Ra101DHh0=,tag:yVY2mSIO/6kMarrhnnjtrA==,type:str]
sops:
    age:
        - recipient: age1kutgmk5ml0lwf4u53h9um8nfdtjdzgftalpxwlwt2zt63h5l450qeyp7zm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArRk41SE1HcFQ0MlJpSjhT
            N25zZVh5aGxkSE1kRzl0TUdzNU5TVmRaaVRFCm5rbVd6TnozTncwRzJNdlV4Uith
            TUdFOE5UVEZ1Y09YMjdaN2xpcGJqNVEKLS0tIEN5eFF5a0d6ZGtWRVJzUXp6eDlV
            YXVuTmNOeXJaMXdTR1c0WmtGVmpzK1EK/Fz967fe113GYRFJQHbIoswOrq8km+qs
            v4AksamIJotWf6j3ieRjtmu9SeuQmgbbpsCKLTpUId0s5otBJXw6Zw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-20T08:37:44Z"
    mac: ENC[AES256_GCM,data:QeEA2TZYBAL9q0rz+vgRdZjm1G31hARSoA0WmPoDruA6PMBO3Nck/TPkUwbKV4hY+weK2TTQKLbqCAliX8tTq8dbjTaGnMEbKbktdjic+S1D+u9CsxOuvjuhHv/k1nJVKDmxUuWTRjSJFvanPZKfVrV2Nv+YkaspHNngPLcfAlQ=,iv:sY92mJGVmhexM4Gjol0KqY3RMAsjtK08G43DNLfec6o=,tag:2u/IGbv8mBG7Uc8/sU54EA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
