apiVersion: v1
kind: Secret
metadata:
    name: mikrotik-exporter-config
    namespace: monitoring
stringData:
    config.yaml: ENC[AES256_GCM,data:F0bt465we3CxVMvVlvIBlEtbJw3rWaolflDo7+vNfhv+190oNKDldwMWReWWnxrjXyWKVuVJ3WVbA9p8NGe+gXzjIVzXQx8svwBqL7VRy/rnSHie2eaiqaNsO51udYGK57VzM3CCHINcJ62QqCFaLrHHwrnTt2FxuZF6TYjoc34b/x1eHBse7QegKqb4sIlgtTKJQgBUz6vfcHqjdYSMdwi9Hjlu4D1bM+5+M02zh4+Qmr6lSRSoq+yuLS/fTqtaTWU+Bhhs4nztSzOcvXYvP+ny3CiXIYTwmNuLANTULsS/eNqEqNiHM2IclApgSX8xaakeAtmC0Y0yVwaPNaPcOZE9rmn4cbAyLQYKvxgbRUSVJjJiuU2wV6u+jmvtjrSVvkvuPzrsA90HsuS3z1SnImQyO8VdN/YJCrj86Xl7ylmvAixNAMqBVE+Gyrgrmo00K33OHVBRPZUocJc=,iv:/YEA8X7j9Fm3RvtDEC4ilfAS+baIpLvNUNboyMUqZR0=,tag:1j/p31TnvOF5P570tnqnmA==,type:str]
sops:
    age:
        - recipient: age1kutgmk5ml0lwf4u53h9um8nfdtjdzgftalpxwlwt2zt63h5l450qeyp7zm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiV1NCK0NWN0lQMWU2aXBL
            TWpTMzFKSThxbkR1UFE3S1dkV2UzQ0pUN25jClYzTzk2UHBrSlhUQmNIOHBrZVZK
            T0owajFhaDA2UW45aU4rWEtqaTlmQkkKLS0tIEFNOEEwRkZSTTR2VHZsSHF6bFNi
            TFhrbUVwMzBucVZDMDdvb0FxMnRIdEkK4ClsC9Y8oaFc7nC9AIwnDK6KqlL9xg1/
            uRPaAqjtJ2jbvVfOQ5WU0PzpBQTyWfFKctV5oSmB2hxiOYT823QR2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-25T05:58:19Z"
    mac: ENC[AES256_GCM,data:OCBcdsAw2snddrrm0urZy2YCxhTnfzRCdOthrgaxl25KCDszuMkR3OrDeROKPRih8+5Ect7DPAIhi/us9gpfslYp8PI//3jlkiWUDj2S/IJfoTzRfOobF2T94aOEOsNsRVPEVz/Jrn/laztgTFZAJrrzBQyaRC1sPCCQBEGCTe0=,iv:ywCXr7IMwZS24TMX81UHhEegxOEv964dkhrZlM8PTsY=,tag:yZS15XnXpfUhcaSTI/53og==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
