apiVersion: v1
kind: Secret
metadata:
    name: unifi-poller-config
    namespace: monitoring
stringData:
    up.conf: ENC[AES256_GCM,data:jrYWm/pjTB8RQy7UJG1qL/G8D7x1Hpxk7uOspreJNNEw/ecjbXheCd+sgWj9WQjoDiBqmCzj0Z0ilWol35Q0ANLqpmrdcyVBN/I1rm4JSZySCvrQOspss3D9SPJxhYlaiLiT7HLiAH7br8DddLkXMVQkUxVkToZjKsQotDbdEXorZrMaKFnAddoMmVe4SgJPkumFy9W+0hX3KOLgxqgpisGTsE81AqHo2Qb2luilatUji3OJ0EJ903lMC1XG+PYFf4AMM4hOsJIixZrMgAiWVpN+f4cHGXatCY7VqRSckYZCYmkSrwt5Yi0SQRZaZYcVAhw0zL8N96hqiaxfDlIjp+V+YWmm9IlRfE2nQ1ais96zmPlZ08RxwD9Gm+cFg7Vk416ZRRleRPj9Gk3JU0zNM4f6SpT7ufCoF63qYF8CcKNwKjmng6FeWBJ8VIQ9qbaz4sM0kXsycc1qk3LNhJijMwX/fU014GnaQCYeSCEG/faV9YaiXIOBX3w1MufKmYbGqewLvEaNvkgwhE+yIfXcegHhpXrgYuuFZ/rLZo6XvFAar5QbJPjJwByarBOgh3TixU88B3OjUZrViYX1ZPqn8LSkUkYPbuaJWlKBVJdftOZwf6iqx+Z247QDua9gZqsO6Mv7WTNUJoDdb5N2DtxBm57+2a7KltI3pmh44QPTbJvBBaYly6Se43dz9VuZQIOfIyEYHbiCYvhuOqWl+7ysThx743Pz7Yi4lNwFbwI5HB1EOcOGkZaRZlXZwH79w3/i6cczZuBEw8FTZdWFQb6vHbeJBs++zKal+WUklcJkm+Pm23sDLmMg6WQfutdyUL3V5ywnNLuGIeEsz91v9wvQk1tz,iv:xKvFsMzzpYefKwEMAccuYb/1JaKUuKfFyakcQcW91DE=,tag:O/h4zK2WgFlBBotW9UfDWA==,type:str]
sops:
    age:
        - recipient: age1kutgmk5ml0lwf4u53h9um8nfdtjdzgftalpxwlwt2zt63h5l450qeyp7zm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjMkZlMFczTmVJNUNzR3NN
            Mjk1U2pEcWl0VVNYUFYrbVRMQ1RTT2pRTTBJClhNZllEVUVFZHZBZmpQd29wMlFR
            NTVDdklSMHNiak50T1FhT2tHL0dxbVUKLS0tIFJMS0QrOXRqaWI3cWxNNWNRVHRx
            ajRua0FXbjFTaW9ISDBRRDFpbW1rSlkKtmwX0qp8q7IKYVdCZlqPvQzu5Gv8hBP8
            E/00nBYAfjr+k/OvU6+stD4+nxVBeitVoqnOK5P9JmseFmiWQwNDdQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-02T02:58:15Z"
    mac: ENC[AES256_GCM,data:D3Vv1TdYWGKsMy6pIWm1MN+9LasYrNYoO4uhr0+BGH9huUcPkfTTxHnfoydW5kKenQG7NIu2bYmrH1xDENqeIkyEtyy/D4vWlVLinKnDONvDNWW8AFHgegFfXb1HaNq5mqL8+1fIKTKxtwIvGw89PHs0vVtdxixNsD1xkK6NlYk=,iv:8utkBqvUav7JnJZeyc/qIijLySMrBMir/Qek79dypO0=,tag:FjRqDrwKhQo1bclyFS8GZg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
