apiVersion: v1
kind: Secret
metadata:
    name: unifi-poller-config
    namespace: monitoring
stringData:
    up.conf: ENC[AES256_GCM,data:oyaLTvoOIwnaMaiagLTzY72sGbGVMTtBr52jmBfQm/tkayAhRhVu4Y5xuuSu7SyraPqou1VRLJAANd5JN6Y1TctSGZcw1VXWbrbyDsuHOvRLmzKZC4mtZzEYBw5O5gZuGLAV79SUwxij59jQALGJaRH400QIbHW29PQ413gAdAJ8WL2hfcdpmH61Xyy8dThLDZZt0QNrF9WfFuIoAMrWd9C7NLNyJENF546nA+Ytu/MuKOoCGsLO9M4KdhP5/v8/GviqgSXkWDGMB3GRdvkTnx9YhCw5T7FUkR3uKTrD83B/zxguOpIF13sgn4upuml0W+aIxYfn7RaK6M1B0RlXVJDpGP/f1Qk/RXepFUbGpnwjMEzbZk3WoOZJ1gOI3r6ik+C9UV8N0sgj3HNbzN1cWEwBk64RHQLUmEBmhC1Zb+FH9jYrUfBhWlwzZMkZt2Nv0e8F9BrG+5R0FNA/mz7awJw784Q+jUTuEguCzCjgvisbelu8s+MTTlhrPu5Buma+VJ5ADWjC/eBMdxLDsSfc5ltMX/inlm6SbGOB37I4F5StYYnurhkBBEBBRAwVOrIf9Zgz3anB,iv:40Yres+m2ogXH8RJ8RZPBgwD8UDlRaKLaTB3Vt4CcmE=,tag:YG/o4zW3oykCRJb0W19EfQ==,type:str]
sops:
    age:
        - recipient: age1kutgmk5ml0lwf4u53h9um8nfdtjdzgftalpxwlwt2zt63h5l450qeyp7zm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyOFlMUnFuZlhCN0xwcnRq
            ejY4SVdaTkdLWGpOTjVFbjc1MVVuOHNxMlU4CnZlNDVSMjlRS3RvMGYvSUtSUkJI
            dGlsdS9ockwxelg2aEtYN2QyY2xHNkEKLS0tIFg2MG56QzhGbkFtaGg1UVhZN0NR
            Q21BbnhtTVRIdXlNN2NIVnJRemRNNk0KdL6I1Vnvi3ioiX5VivCT3nHOSqfVtCWe
            DpFElKQVmsIiQnvCxnCcPCAAwaWYPXXugBjT/hzNOTGXJZSVu5FIww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-02T02:52:32Z"
    mac: ENC[AES256_GCM,data:aicA6AKpGmXxPEgd4jb8RQUGn7gvaLb/1DgZWD2cpqjpdiDB4iVyhF88KQvGEnSg3dHhK4JzR5+ONrPqCGJeRv78Gt4Zfrm4bgX+0YV8NHMQbWtwPP67s3co1y97OyWhcK7/N7jhFi06AjVSXl1vbNcnwbGOSYncnqoJlyovRp8=,iv:tKBAecsj2RZnmoiMWBeB4qbihAur/w3uYW0lZNtiVNE=,tag:W/DN/Ehabq2N3JLOevL71Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
