apiVersion: ENC[AES256_GCM,data:cwE=,iv:YOBNQ2Lj7EXebuFqGsMkh8UeaCKgwtPjRHR6V41jdls=,tag:EaV9YXUON691nm6gL1LIBg==,type:str]
kind: ENC[AES256_GCM,data:X+4oHkg1,iv:TGx9RSv3BRPjW8ksbSurhel+SleY5ADnLwhBvI8+J9c=,tag:IDXB6xfgMcpmMgIm1SvuOA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:biar9am+RxcmP1KGv/M3qho2B7E=,iv:pyDcvA8W/vdDWEBGci97PU9AErfntRQUjOAdwq18oAk=,tag:FsRiQPVo9bwvY5IxbBusIA==,type:str]
    namespace: ENC[AES256_GCM,data:9dYfiZBCwp8v8Tw6,iv:4rIhCqeXLjbpGdexxP+x0nNogAMEVGqFCjHQscZhg4Y=,tag:EofMO2fJYywGvLXlIHnQKg==,type:str]
type: ENC[AES256_GCM,data:VjdYp6zA,iv:O1lwh+WVMlFBzUjeT29pH9QdT4G2JdUhQvkEIBseNq8=,tag:VJ39Te4y2vMLg2aRK297Bw==,type:str]
stringData:
    api-token: ENC[AES256_GCM,data:1uoqdgyocNBi2tkOfHabalY64zVJ5ohRpl4vspxwFZzwXWLVtcezurwkajy8xebDQuEF+s8=,iv:EPuT7oJ/krRpUCAIRa4zKlPeJu13RJdOMtdzmWeIfN0=,tag:42qZQZkPiuMmoeOWoFbetQ==,type:str]
sops:
    age:
        - recipient: age1kutgmk5ml0lwf4u53h9um8nfdtjdzgftalpxwlwt2zt63h5l450qeyp7zm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByUVdQb0M2ODV2Q3JwWDYz
            Q2xaN1dJSTAyU1JvaFpqNTlIRjc1akJFYmhZClNoK0YyQnIvWjdobWdZdzlhNkRH
            dlFXMkxvWDJlVlZHbkdhQVQyM2JUTEEKLS0tIG1FR1pncHplQTBSTDl6TGJhYlFO
            YjZQYW9UcExrT0ZVdGNrZEdtbHJ6OUUKnyuy9IVl895whZN3hxcE12jSs5v+OzIe
            392tsqFG1f8JE7nmeZN+hDIjH4i8OTpwtqk7LS/ZgQe5p3QQkgJNFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T15:14:13Z"
    mac: ENC[AES256_GCM,data:rbaxG2V5vOmNXPp0tEPJXL1I6DrNkglJxrdEmkdjB5Km/NVRk4CRSKHnFtn6aXCscPf8WwZE+y8ToOgsLNHWPfJJiow76Bdf9w+t0Zv4X8rg3kdOTUGSb69pnX0uw6NEgr0iZJ57FvgCGQcN4p4pV0b+NLQ8fSSDO9BlhPJAzNI=,iv:HLgHHpjMJFFcRclZ6SaI2YHtFxGjRKhAFLDQdBWwbcQ=,tag:J9hACIoFaqdWqM/qQXCGUQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
