apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
    namespace: authentik
type: Opaque
stringData:
    secret-key: ENC[AES256_GCM,data:Im08W6yFUoAtaEgjRcnYvWM85yf33ehKyz9WXO/oWMlNv/b/kZ+I4918igXc/ESVdhU=,iv:LhNLIwIzerDoW0SKygle3qWJwfwfxhUTI431Dhdaw8c=,tag:a9k4oOx2h+yO+VGSzWBqHw==,type:str]
sops:
    age:
        - recipient: age1kutgmk5ml0lwf4u53h9um8nfdtjdzgftalpxwlwt2zt63h5l450qeyp7zm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBZGN6S2dMSVVURzlnTmtT
            d2R4OUVUUndpS1dEV1RXb3FtMnVqclhFNUQwCm42Ulc4RDZtdDNMamxSWDJwNUwr
            VkVPMVh6U0lnaENYMWJKQzRaWHdjL0kKLS0tIGhFbDlmUndXZVM4L3lZMEdqYi9V
            ZjNoNUsrNGFLL1QzbTVIdk82elM5Zm8Kmt57+WNqUd4TL0s4kGLcGYJXlPavgxd1
            M/NBw+gtrRUyInK/Nqrzvg2cnHX6JPJwY0STunRHRMrS4KqsGf/c4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T13:41:25Z"
    mac: ENC[AES256_GCM,data:vK6EhAIDjhwByf/xZu4kb16ETO7JbY2hug7Gfd5CpDe7Bm2h64qAZjWccngxq64r1TXmbsdLGHd6l+BGEQ+AqrTRUR3Fut3jqd9VoPcebNB9zljE1dUXJNQcZM9UT5xcfw4THQKc+oH87+N9IL9jCrwIsx9WJJy68NreejSq8Wo=,iv:qSj3hMvWiabZ8XmcMd8xV0ThwkExE5+sbSuZ9HyKOPI=,tag:dMLKlUw590zCLr1fn/0Z0A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
