apiVersion: v1
kind: Secret
metadata:
    name: authentik-db-credentials
    namespace: authentik
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:QMwlV82afrrF,iv:ZBH1LKJW3xrxaRqdVDbIntqqIlEP9US8H55QzdUEm6I=,tag:o2Axv7vY/3d1U+37MZzaSg==,type:str]
    password: ENC[AES256_GCM,data:CaCXOuc6z/YW2FOFmK25K3BUARwmvbaZZn/cFE3WZ5c=,iv:syr7uCsVUTIPjdc9THjMDdw5ysUb0r4JTWWc/9N1Q/I=,tag:qFigD/YZr1Z193NG1d+Abg==,type:str]
sops:
    age:
        - recipient: age1kutgmk5ml0lwf4u53h9um8nfdtjdzgftalpxwlwt2zt63h5l450qeyp7zm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCRzkyS2wyZTAwc2F4anFl
            WDVic29xMXdEbXVFTmxxZGpqSXhUQzd1am4wCkVXWXFkVUh0SjBQRXJoYkQ5c1Zh
            Z2NDMThoU0ZCMUpsdTVQN3RRTnpsbDgKLS0tIEZRYk9QYmM3K054NEZpd3dHZTMr
            cTh3a0xQQW1qdTExYUtwTk9ZdjREYWMK5ztFU7zUMFsDqpoGe8XK97XyuoCLsInq
            yfWUWqH3YvP6bJ+CtYsElRj+o3H5mmUE4qo4lMWvyOS3vbTa+wZAgw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T13:41:25Z"
    mac: ENC[AES256_GCM,data:s1VK9ZxUxYehy1055gD7UT0guVTTc4GAgLZdA+rUm9LIrmeesyDIoFnvE+fINtuqNHHvjcmtmPBf/QmIewAsdlvok5iXmrMW8lJ1fGxQSrJLzCPWF/AoaAwYMyvz/VSkvWBrwxId5GPwRif7Li78oudrRQY1XvJX0dQrRje8uf8=,iv:BgrrA0WWrd47GBeq20NxQpUMMsx4CGnMT/gQhiO5Jtc=,tag:zxqv6R260sVUEtC6iN0F7Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
