apiVersion: v1
kind: Secret
metadata:
    name: kea-db-grafana-credentials
    namespace: kea
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:RqX7hSasoziE5Q==,iv:dhTOQMxNvggSqpGeMpsGGvSLjGBuNhNAbGQTFc+iNjE=,tag:s6GUiuNmc+lepWK11RgKEQ==,type:str]
    password: ENC[AES256_GCM,data:616sz2gDDq5DkySadK47PHJV8Q==,iv:a4uS/M9zvfyRcDZ/pqgkCnyAkdjcnM4t4vUjZiRLOcg=,tag:oQ2f5gEEP4JLscKtR6zWKw==,type:str]
sops:
    age:
        - recipient: age1kutgmk5ml0lwf4u53h9um8nfdtjdzgftalpxwlwt2zt63h5l450qeyp7zm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzbnloS2kvcnp3STF4WVdK
            VTZoa05ndkp4Z1gvQ3BOL2dTMXJGOEdtUzNRCllLRVFyOEtSREZXbS8zSkluejl2
            WEVKNmlMRjlCOENBS0RkNVRRSlhoaUUKLS0tIGZpazVBQUNpRTNhL0FNYzRYeWVi
            S1pMN2FzVE81bmxjVklITUlNUklnemcK8/twDWbovkzS95pOkH6ImdylUKAshnc6
            twDVeqjaWWZqmTMHIlMbACxLUlx5qDDj041E99JAjnl1uQPZXRHKxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T15:19:45Z"
    mac: ENC[AES256_GCM,data:CWGapXAfnQOyeuY3Tt9mKotjdqPuXggX7PoSImS4etV0yze4DRdmC4GjnDeAH+bCCPRuuniQAovytRQ6bDJCgAuC2LktL+WIFovzACQLyFVdiME4HiH5EgLpDNX98YC5aG3mQ/AsQ2zBj0Ug1v3h7UzdGo/gSB7KoOJoKqQ1uiI=,iv:JuFsM2izmKZLC45Nyp8I7wghQuK+YHQN9sCLCNDSOqQ=,tag:f8Nu0rnMZqZxWsLTA8DJag==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
