apiVersion: v1
kind: Secret
metadata:
    name: kea-db-credentials
    namespace: kea
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:rajv,iv:RA3xaBEXbnN3jX+0ztSHWkg+D/FbVJKpr4NTCIcuvzY=,tag:/k/0g4r3lN/IZjI6V3V9tw==,type:str]
    password: ENC[AES256_GCM,data:jzpiTYEBYQELIBAmkR0SgormkL3fQw==,iv:iXuF7yGS046zcQHNlx0e6S2ACps/xaE91qZ9vkMz+zA=,tag:P/jLv/LM3Vs62R+/3PunKQ==,type:str]
sops:
    age:
        - recipient: age1kutgmk5ml0lwf4u53h9um8nfdtjdzgftalpxwlwt2zt63h5l450qeyp7zm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGdmpSSllXVi9Mam1sNFJo
            L1dFcVRxclFzc0J3b0d5NXE0d0lXVy9kOEQwCmlleDVOMWszS1EvL3gwNGlib3pX
            MDJ2YmZaQ1pIS05qaS85QmRnVDJ6OWMKLS0tIEpQditheG5FSHdMSmM2RU5OSFRZ
            RVJLdTFGRGo0dHQzQkhzN1gyQXdlYlUKKSbghhchQ3dmvGZg+JAecNOjbzve/cR5
            Uv7x+v9pXXdj+H2nJzRR+Coo6aPxR8WSjYxyK+bBhsqGyPm30SkzAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T15:19:45Z"
    mac: ENC[AES256_GCM,data:SIveBLia5LNnrQl0+bKvBvf9QVVdxBf/wPO+x+hcYMQMLsASq/Ne9p2RKFXemkMGMwiVIddYcdqONq6+XuacPrNTpz8rFO3yONRif6KmA2zIQ84lKnkcue1/dLVe+k5kX24+FtQoRK+3iFc8ht9inPT+uOw5MRN1Php6JMtTkq8=,iv:h/nl/6wgeFXZwy4cBdVe/Fyj09VxAIWBxkS9xC17bhE=,tag:nt/gPhSQEKrjPvuN7RuW4g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
